[package]
name = "makepad-live-compiler"
version = "0.5.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad platform live DSL compiler"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "syydsVL84Wg1XgRpcxLFZQtLGrs="

[dependencies]
makepad-derive-live = { path = "../derive_live", version = "0.4.0" }
makepad-math = { path = "../../libs/math", version = "0.4.0" }
makepad-live-tokenizer = { path = "../live_tokenizer", version = "0.4.0" }
#tracing = "0.1"
